version: '2.124.2.{build}'
pull_requests:
  do_not_increment_build_number: true
init:
- ps: (new-object net.webclient).DownloadFile('https://go.microsoft.com/fwlink/?linkid=838401', "c:/dotnet-install.exe")
- ps: Start-Process c:\dotnet-install.exe -ArgumentList "/install","/quiet" -Wait
build_script:
- ps: dotnet restore --no-cache
- ps: dotnet build .\Docker.DotNet\Docker.DotNet.csproj -c Release
- ps: dotnet build .\Docker.DotNet.X509\Docker.DotNet.X509.csproj -c Release
- ps: dotnet build .\Docker.DotNet.BasicAuth\Docker.DotNet.BasicAuth.csproj -c Release
- ps: nuget pack Docker.DotNet.nuspec -properties version=$($env:appveyor_build_version)
- ps: nuget pack Docker.DotNet.BasicAuth.nuspec -properties version=$($env:appveyor_build_version)
- ps: nuget pack Docker.DotNet.X509.nuspec -properties version=$($env:appveyor_build_version)