version: 3.125.3.{build}
pull_requests:
  do_not_increment_build_number: true
init:
- ps: (new-object net.webclient).DownloadFile('https://dot.net/v1/dotnet-install.ps1', "C:/dotnet-install.ps1")
- ps: C:/dotnet-install.ps1 -Channel 2.0
build_script:
- ps: dotnet restore --no-cache
- ps: dotnet pack -c Release -o $pwd --version-suffix $($env:appveyor_build_number)
test: off
artifacts:
- path: '*.nupkg'